Replace thermal buoyancy flux label from buoyancy_flux to thermal_buoyancy_flux

diff --git a/tests/Dynamo_Benchmark/Dynamobench_Case2_cont/Makefile b/tests/Dynamo_Benchmark/Dynamobench_Case2_cont/Makefile
--- a/tests/Dynamo_Benchmark/Dynamobench_Case2_cont/Makefile
+++ b/tests/Dynamo_Benchmark/Dynamobench_Case2_cont/Makefile
@@ -66,6 +66,11 @@ test:
 	fi
 	
 	$(TARGET_COMPARE_PSF)
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed sectioning data check'; \
+		exit 1;\
+	fi
+	
 	@echo 'Dynamo Benchmark Case 2 continue check finished'
 
 clean:
