Replace test packages to stop if error happened

diff --git a/tests/Communication_check/gzip/Makefile b/tests/Communication_check/gzip/Makefile
--- a/tests/Communication_check/gzip/Makefile
+++ b/tests/Communication_check/gzip/Makefile
@@ -4,30 +4,23 @@
 #
 SHELL           = /bin/sh
 #
-#  directories of Kemo's Dynamo toolkit
-#
-SRCDIR = /Users/matsui/src_kemo
-#
-MHDDIR =  $(SRCDIR)/MHD
-BUILDDIR= $(SRCDIR)/bin
-TESTDIR=  $(SRCDIR)/tests
-#
-# MPI settings
-#
-MPICHDIR =    
-MPICHLIBDIR = $(MPICHDIR)/lib
-MPICHBINDIR = $(MPICHDIR)/bin
-MPICHINCDIR = 
-MPILIBS =      
-#
 
 all: test
 
 test: 
-	rm -f *.dat
-	$(MPIRUN) -np 6 $(BUILDDIR)/utilities/gen_sph_grids > log.txt
-	$(MPIRUN) -np 6 $(BUILDDIR)/tests/check_sph_grids >> log.txt
-	$(MPIRUN) -np 6 $(BUILDDIR)/tests/check_sph_comms >> log.txt
+	rm -f *.dat *.txt
+	$(MPI_GEN) > log.txt
+	$(MPI_CHECK) >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed spherical shell grid check'; \
+		exit 1;\
+	fi
+	$(MPI_TEST) >>  log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed spherical shell communication check'; \
+		exit 1;\
+	fi
+	@echo 'Gzipped ASCII indexing file is correct'
 
 clean:
 	rm -f *.dat *.txt mesh/in.*
diff --git a/tests/Communication_check/no_file/Makefile b/tests/Communication_check/no_file/Makefile
--- a/tests/Communication_check/no_file/Makefile
+++ b/tests/Communication_check/no_file/Makefile
@@ -8,24 +8,25 @@ SHELL           = /bin/sh
 #
 SRCDIR = /Users/matsui/src_kemo
 #
-MHDDIR =  $(SRCDIR)/MHD
-BUILDDIR= $(SRCDIR)/bin
-TESTDIR=  $(SRCDIR)/tests
+NP = 6
+MPIRUN= mpirun
+MPI_TEST =  $(MPIRUN) -np $(NP) $(SRCDIR)/bin/tests/check_sph_comms
 #
-# MPI settings
 #
-MPICHDIR =    
-MPICHLIBDIR = $(MPICHDIR)/lib
-MPICHBINDIR = $(MPICHDIR)/bin
-MPICHINCDIR = 
-MPILIBS =      
+#  -------------------------------------------------------------------------
 #
+
 
 all: test
 
 test: 
-	rm -f *.dat
-	$(MPIRUN) -np 6 $(BUILDDIR)/tests/check_sph_comms > log.txt
+	rm -f *.dat *.txt
+	$(MPI_TEST) >>  log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed spherical shell communication check'; \
+		exit 1;\
+	fi
+	@echo 'Indexing is correct'
 
 clean:
 	rm -f *.dat *.txt
diff --git a/tests/FFT_test/Makefile b/tests/FFT_test/Makefile
--- a/tests/FFT_test/Makefile
+++ b/tests/FFT_test/Makefile
@@ -8,17 +8,7 @@ SHELL           = /bin/sh
 #
 SRCDIR = /Users/matsui/src_kemo
 #
-MHDDIR =  $(SRCDIR)/MHD
 BUILDDIR= $(SRCDIR)/bin
-TESTDIR=  $(SRCDIR)/tests
-#
-# MPI settings
-#
-MPICHDIR =    
-MPICHLIBDIR = $(MPICHDIR)/lib
-MPICHBINDIR = $(MPICHDIR)/bin
-MPICHINCDIR = 
-MPILIBS =      
 #
 
 all: test
@@ -26,14 +16,29 @@ all: test
 test: 
 	rm -f *.dat
 	$(BUILDDIR)/tests/test_FFTPACK
+	$(BUILDDIR)/tests/compare_fft_test < compare_FFTPACK.txt > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed Gauss points check'; \
+		exit 1;\
+	fi
+	
 	$(BUILDDIR)/tests/test_FFTW3_f
+	$(BUILDDIR)/tests/compare_fft_test < compare_FFTW3.txt > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed FFTW3 check'; \
+		exit 1;\
+	fi
+	
 	$(BUILDDIR)/tests/test_single_FFTW3
-	echo 'Compare section and isosurface data'
-	$(BUILDDIR)/tests/compare_fft_test < compare_FFTPACK.txt
-	$(BUILDDIR)/tests/compare_fft_test < compare_FFTW3.txt
-	$(BUILDDIR)/tests/compare_fft_test < compare_single_FFTW3.txt
+	$(BUILDDIR)/tests/compare_fft_test < compare_single_FFTW3.txt > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed single FFTW3 check'; \
+		exit 1;\
+	fi
+	echo 'FFT check finished'
+
 
 clean:
-	rm -f *.dat
+	rm -f *.dat log.txt
 
 distclean: clean
diff --git a/tests/Gauss_point_test/Makefile b/tests/Gauss_point_test/Makefile
--- a/tests/Gauss_point_test/Makefile
+++ b/tests/Gauss_point_test/Makefile
@@ -10,24 +10,18 @@ SRCDIR = /Users/matsui/src_kemo
 #
 MHDDIR =  $(SRCDIR)/MHD
 BUILDDIR= $(SRCDIR)/bin
-TESTDIR=  $(SRCDIR)/tests
-#
-# MPI settings
-#
-MPICHDIR =    
-MPICHLIBDIR = $(MPICHDIR)/lib
-MPICHBINDIR = $(MPICHDIR)/bin
-MPICHINCDIR = 
-MPILIBS =      
-#
 
 all: test
 
 test: 
-	rm -f *.dat
+	rm -f *.dat log.txt
 	$(BUILDDIR)/tests/gauss_points < input.txt
-	echo 'Compare section and isosurface data'
-	$(BUILDDIR)/tests/compare_gauss_points < compare.txt
+	$(BUILDDIR)/tests/compare_gauss_points < compare.txt > log.txt
+	@if [ `tail -n 1 log.txt` != 0 ]; then\
+		echo 'Failed Gauss points check'; \
+		exit 1;\
+	fi
+	echo 'Gauss points check finished'
 
 clean:
 	rm -f *.dat
diff --git a/tests/restart_assemble/ascii/Makefile b/tests/restart_assemble/ascii/Makefile
--- a/tests/restart_assemble/ascii/Makefile
+++ b/tests/restart_assemble/ascii/Makefile
@@ -8,26 +8,26 @@ SHELL           = /bin/sh
 #
 SRCDIR = /Users/matsui/src_kemo
 #
-MHDDIR =  $(SRCDIR)/MHD
-BUILDDIR= $(SRCDIR)/bin
-TESTDIR=  $(SRCDIR)/tests
+# Command settings
 #
-# MPI settings
-#
-MPICHDIR =    
-MPICHLIBDIR = $(MPICHDIR)/lib
-MPICHBINDIR = $(MPICHDIR)/bin
-MPICHINCDIR = 
-MPILIBS =      
+MPIRUN= mpirun   
+TARGET_GEN_SPH_GRID= $(SRCDIR)/bin/utilities/gen_sph_grids
+TARGET_NEWSPH= $(SRCDIR)/bin/utilities/assemble_sph
+TARGET_CMP_SPH_RST=  $(SRCDIR)/bin/tests/compare_sph_restart#
 #
 
 all: test
 
 test: 
-	rm -f *.dat restart/rst.*
-	$(MPIRUN) -np 3 $(BUILDDIR)/utilities/gen_sph_grids > log.txt
-	$(MPIRUN) -np 3 $(BUILDDIR)/utilities/assemble_sph >> log.txt
-	$(MPIRUN) -np 3 $(BUILDDIR)/tests/compare_sph_restart >> log.txt
+	rm -f *.dat *.txt restart/rst.*
+	$(MPIRUN) -np 3 $(TARGET_GEN_SPH_GRID) > log.txt
+	$(MPIRUN) -np 3 $(TARGET_NEWSPH)  >> log.txt
+	$(MPIRUN) -np 3 $(TARGET_CMP_SPH_RST) >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed ASCII Data assemble check'; \
+		exit 1;\
+	fi
+	@echo 'ASCII Data assemble check finished'
 
 clean:
 	rm -f *.dat *.txt restart/rst.* sph_lm7t12r14c_ic_3/in.* 
diff --git a/tests/restart_assemble/merged_bin_gz/Makefile b/tests/restart_assemble/merged_bin_gz/Makefile
--- a/tests/restart_assemble/merged_bin_gz/Makefile
+++ b/tests/restart_assemble/merged_bin_gz/Makefile
@@ -8,25 +8,25 @@ SHELL           = /bin/sh
 #
 SRCDIR = /Users/matsui/src_kemo
 #
-MHDDIR =  $(SRCDIR)/MHD
-BUILDDIR= $(SRCDIR)/bin
-TESTDIR=  $(SRCDIR)/tests
+# Command settings
 #
-# MPI settings
-#
-MPICHDIR =    
-MPICHLIBDIR = $(MPICHDIR)/lib
-MPICHBINDIR = $(MPICHDIR)/bin
-MPICHINCDIR = 
-MPILIBS =      
+MPIRUN= mpirun   
+TARGET_GEN_SPH_GRID= $(SRCDIR)/bin/utilities/gen_sph_grids
+TARGET_NEWSPH= $(SRCDIR)/bin/utilities/assemble_sph
+TARGET_CMP_SPH_RST=  $(SRCDIR)/bin/tests/compare_sph_restart#
 #
 
 all: test
 
 test: 
-	rm -f *.dat restart/rst.*
-	$(MPIRUN) -np 6 $(BUILDDIR)/utilities/assemble_sph > log.txt
-	$(MPIRUN) -np 6 $(BUILDDIR)/tests/compare_sph_restart >> log.txt
+	rm -f *.dat *.txt rst.*
+	$(MPIRUN) -np 6 $(TARGET_NEWSPH)  >> log.txt
+	$(MPIRUN) -np 6 $(TARGET_CMP_SPH_RST) >> log.txt
+	@if [ `tail -n 1 flag.txt` != 0 ]; then\
+		echo 'Failed Merged gzipped BINARY Data assemble check'; \
+		exit 1;\
+	fi
+	@echo 'Merged gzipped BINARY Data assemble check finished'
 
 clean:
 	rm -f *.dat *.txt rst.*
